sudo: false

language: node_js

node_js:
    -    12

dist: trusty

addons:
    chrome: stable
    
before_install:
    -   google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
    directories:
        -   ./node_modules

install:
    -   npm install

jobs:
    include:
    -   name: webpack build
        script: npm run build
    -   name: test
        script: npm test
        

    